# This is a basic workflow to help you get started with Actions

name: Vercel Upload
on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2-beta
    - name: Generate `.vercel/project.json`
      run: |
        mkdir $GITHUB_WORKSPACE/.vercel
        echo "{\"orgId\":\"${{ secrets.VERCEL_ORG_ID }}\",\"projectId\":\"${{ secrets.VERCEL_PROJECT_ID }}\"}"> $GITHUB_WORKSPACE/.vercel/project.json
    - name: Generate `.vercel/project.json`
      run: |
        npx vercel \
          --token ${{ secrets.VERCEL_TOKEN }} \
          --no-clipboard --prod --confirm \
          -m githubCommitSha=${{ github.sha }}, \
          -m githubCommitAuthorLogin=${{ github.actor }}, \
          -m githubDeployment=1 \
          -m githubOrg=${{ github.repository_owner }}, \
          -m githubRepo=${{ github.repository }}, \
          -m githubCommitOrg=${{ github.repo.owner }}, \
          -m githubCommitRepo=${{ github.repository }}, \
          -m githubCommitRef=${{ github.ref }}, \




